/**
 * Writes the YAML frontmatter block for an article.
 *
 * This is string *serialisation*, not string *interpolation*, and the difference
 * is the whole reason the file exists. The deploy is gated on `astro check &&
 * astro build` (plan, constraint 2), so a title Francesco types on his phone —
 * containing `'`, `"`, `:` or `—`, all of which are YAML syntax — must not be
 * able to produce a file that fails the build. A failed build is an English
 * stack trace in a GitHub Actions log, which is the one error he can neither
 * read nor fix.
 *
 * The output shape deliberately matches the five articles already in
 * src/content/blog byte for byte, because those files are the contract the
 * schema in src/content.config.ts was written against.
 */

/**
 * YAML single-quoted style: the only thing with special meaning inside is the
 * quote itself, escaped by doubling. `:`, `#`, `"`, `—`, `[`, `{` and leading
 * `-` are all literal in this style, which is exactly why it is the right one
 * for prose written by someone who has never heard of YAML.
 */
function quote(value: string): string {
  // Control characters and newlines have no legal place in a single-quoted
  // scalar on one line. Collapsing rather than escaping keeps the file readable
  // and means a pasted multi-line title degrades to a long title, not a break.
  const flat = value.replace(/[\u0000-\u001f\u007f]+/g, ' ').replace(/\s+/g, ' ').trim();
  return `'${flat.replace(/'/g, "''")}'`;
}

/** `YYYY-MM-DD`, which the schema's `z.coerce.date()` parses unambiguously. */
function isoDate(date: Date): string {
  return date.toISOString().slice(0, 10);
}

/**
 * A photo key is generated by us (`blog-<slug>-NN`) or chosen from the 46 curated
 * ones, so it is always plain — but it is written unquoted, and an unquoted
 * scalar that started with `[` or contained `: ` would change the document's
 * shape rather than fail loudly. Quote anything that is not obviously safe.
 */
function bareOrQuoted(value: string): string {
  return /^[a-z0-9][a-z0-9-]*$/.test(value) ? value : quote(value);
}

export interface ArticleFrontmatter {
  title: string;
  description: string;
  date: Date;
  /** Set only when republishing an article that is already live. */
  updated?: Date | undefined;
  locale: 'it' | 'en';
  /** Photo key, not a path — see src/lib/photos.ts. */
  cover?: string | undefined;
  draft: boolean;
}

/**
 * Returns the complete file body, frontmatter and markdown together.
 *
 * Ends with exactly one newline and contains no CRLF anywhere (plan, constraint
 * 6): `.gitattributes` pins `eol=lf`, and a CRLF that slipped through would change
 * Vite's content hashes — which has already caused a 404-on-hashed-asset bug on
 * this site once.
 */
export function buildArticleFile(front: ArticleFrontmatter, markdown: string): string {
  const lines = [
    '---',
    `title: ${quote(front.title)}`,
    `description: ${quote(front.description)}`,
    `date: ${isoDate(front.date)}`,
    ...(front.updated ? [`updated: ${isoDate(front.updated)}`] : []),
    `locale: ${front.locale}`,
    ...(front.cover ? [`cover: ${bareOrQuoted(front.cover)}`] : []),
    `draft: ${front.draft ? 'true' : 'false'}`,
    '---',
    '',
  ];

  const body = markdown.replace(/\r\n?/g, '\n').replace(/\n{3,}/g, '\n\n').trim();
  // Blank line after the closing `---`, matching the five hand-written articles.
  return `${lines.join('\n')}\n${body}\n`.replace(/\r/g, '');
}
